### ISSUE TITLE
Scraping an image doesn't return said image in images[] array

### ISSUE THREAD

**Issue by pdehaan** [mozilla/page-metadata-parser#56]
Not sure if valid use case, but worth discussion somewhere, I imagine...

I looked at some random image on The Internet, http://i.imgur.com/qu1D1i2.png

When I try and lookup that URL via the metadata proxy, it returns a response, but the `images[]` array is empty, even though the URL itself is an image.
Supporting this use case may require too much special casing where we have to inspect the HTTP Content-Type and inject the image if the URL is the actual image (and not an HTML page with scrape-able meta tags).

```sh
$ http https://metadata.dev.mozaws.net/v1/metadata urls:='["http://i.imgur.com/qu1D1i2.png"]' -j -v

POST /v1/metadata HTTP/1.1
Accept: application/json
Accept-Encoding: gzip, deflate
Connection: keep-alive
Content-Length: 44
Content-Type: application/json; charset=utf-8
Host: metadata.dev.mozaws.net
User-Agent: HTTPie/0.9.1

{
    "urls": [
        "http://i.imgur.com/qu1D1i2.png"
    ]
}

HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 226
Content-Type: application/json; charset=utf-8
Date: Wed, 24 Aug 2016 23:29:59 GMT
ETag: W/"e2-8nExhyCWBstSo0Fyi5WAGw"
Server: nginx/1.9.9
Strict-Transport-Security: max-age=31536000

{
    "request_error": "",
    "url_errors": {},
    "urls": {
        "http://i.imgur.com/qu1D1i2.png": {
            "favicon_url": "http://i.imgur.com/favicon.ico",
            "images": [],
            "original_url": "http://i.imgur.com/qu1D1i2.png",
            "url": "http://i.imgur.com/qu1D1i2.png"
        }
    }
}
```

<details>
<summary>`$ curl -v http://i.imgur.com/qu1D1i2.png`:</summary>
```sh
$ curl -v http://i.imgur.com/qu1D1i2.png

*   Trying 151.101.40.193...
* Connected to i.imgur.com (151.101.40.193) port 80 (#0)
> GET /qu1D1i2.png HTTP/1.1
> Host: i.imgur.com
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Last-Modified: Thu, 18 Aug 2016 17:41:22 GMT
< ETag: "ff147ca3989a0d3a1459a68197703c9b"
< Content-Type: image/png
< Fastly-Debug-Digest: 51baf4e16eef201d40ad7972b9cf48d2c78f559e1c1dc2d152ecfdffd5ff2a37
< cache-control: public, max-age=31536000
< Content-Length: 1224831
< Accept-Ranges: bytes
< Date: Wed, 24 Aug 2016 23:38:56 GMT
< Age: 539625
< Connection: keep-alive
< X-Served-By: cache-iad2129-IAD, cache-sjc3129-SJC
< X-Cache: HIT, HIT
< X-Cache-Hits: 1, 1
< X-Timer: S1472081936.673075,VS0,VE1
< Access-Control-Allow-Methods: GET, OPTIONS
< Access-Control-Allow-Origin: *
< Server: cat factory 1.0
<
...
```
</details>

**Comment by jaredkerim** [comment]
Yeah this is a good point.  This is a case where the service can make a decision about how to parse a URL that is completely outside the scope of page metadata parser.  I don't have a solid understanding of how much we expect the service to start doing this stuff.

**Comment by pdehaan** [comment]
@jaredkerim What if we move the logic to the **page-metadata-service**, and check the return content-type of the `fetch()` response?

**Comment by pdehaan** [comment]
Here's some garbage code:

```js
const fetch = require('node-fetch');

fetchPage('http://cnn.com');
fetchPage('http://i.imgur.com/44sTt1l.jpg');
fetchPage('http://foo.bar').catch(console.error);
fetchPage('http://actionscriptexamples.com/foo/buzz');

function fetchPage(url) {
  return fetch(url)
    .then((res) => {
      return Promise.all([
        {
          contentType: res.headers.get('content-type'),
          ok: res.ok,
          status: res.status,
          statusText: res.statusText,
          url
        },
        res.text() // returns a Promise
      ]);
    })
    .then(([meta, content]) => {
      return {
        meta,
        content
      };
    })
    .then(({meta}) => {
      console.log('%s (isImage: %s)', meta.url, isImage(meta.contentType));
      console.log(JSON.stringify(meta, null, 2));
    });
}

function isImage(contentType) {
  return /^image\//.test(contentType);
}
```

<details>
<summary>Output:</summary>
```sh
$ node fetch-test.js
{ FetchError: request to http://foo.bar failed, reason: getaddrinfo ENOTFOUND foo.bar foo.bar:80
    at ClientRequest.<anonymous> (/Users/pdehaan/dev/tmp/del/generator-ra/node_modules/node-fetch/index.js:127:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:308:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at connectErrorNT (net.js:1015:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
  name: 'FetchError',
  message: 'request to http://foo.bar failed, reason: getaddrinfo ENOTFOUND foo.bar foo.bar:80',
  type: 'system',
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND' }

http://i.imgur.com/44sTt1l.jpg (isImage: true)
{
  "contentType": "image/jpeg",
  "ok": true,
  "status": 200,
  "statusText": "OK",
  "url": "http://i.imgur.com/44sTt1l.jpg"
}

http://cnn.com (isImage: false)
{
  "contentType": "text/html; charset=utf-8",
  "ok": true,
  "status": 200,
  "statusText": "OK",
  "url": "http://cnn.com"
}

http://actionscriptexamples.com/foo/buzz (isImage: false)
{
  "contentType": "text/html; charset=UTF-8",
  "ok": false,
  "status": 404,
  "statusText": "Not Found",
  "url": "http://actionscriptexamples.com/foo/buzz"
}
```
</details>

**Comment by jaredkerim** [comment]
This is an issue for https://github.com/mozilla/page-metadata-service.  The parser does not make network requests.

**Comment by pdehaan** [comment]
Moved to https://github.com/mozilla/page-metadata-service/issues/82. Closing.
